application: laliga-1134
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:

- url: /static
  static_dir: laliga/static

- url: /.*
  script: main.application

libraries:
- name: django
  version: latest

env_variables:
  DJANGO_SETTINGS_MODULE: 'liga.settings'
